### ISSUE TITLE
Script not working anymore ?

### ISSUE THREAD

**Issue by ochbob** [carnivorouz/updateOmbi#4]
Hello,

Thanks for this script, but it does not work anymore :/

curl -s https://github.com/Ombi-app/Ombi/releases | grep "tar.gz"  return void

I don't know how to fix, i'm not familiar with scripting

**Comment by carnivorouz** [comment]
Hey,
As of the last update 12/21 I am no longer running or supporting Ombi.  I'd recommend looking into running your request app and other Plex apps as Docker containers.  It's a little bit of setup that is pretty easy through online guides that will pay dividends later on in simplifying management.
